<a href="https://colab.research.google.com/github/rajatgarg01/Pytorch/blob/main/Pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##. pytorch fundamentals
It is open source machine learning and deep learning framework

It allows you to manipulate and process data and write machine learning algorithms using python code

many of the words's largest technology companies such as meta,tesla and microsoft as well as artificial intelligence research companies such as openAI use pytorch to power research and bring mchine learning to their products.

In [1]:
import torch
print(torch.__version__)

2.9.0+cpu


In [2]:
#scalar
scalar=torch.tensor(7)
print(scalar)

tensor(7)


In [3]:
scalar.ndim

0

In [4]:
# Get the python number within a tensor
scalar.item()

7

In [5]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.item()

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

In [8]:
#Check the shape
vector.shape

torch.Size([2])

In [9]:
#matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

#Random tensor

In [15]:
random_tensor=torch.rand(size=(3,4))
random_tensor,random_tensor.dtype

(tensor([[0.5753, 0.5384, 0.9467, 0.0272],
         [0.7966, 0.4234, 0.0961, 0.7052],
         [0.4711, 0.3033, 0.7506, 0.7894]]),
 torch.float32)

#zeros and ones
sometime you have to fill the tensor with zeros and ones

In [16]:
zeros=torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones=torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

#create a range and tensor like

In [19]:
zero_to_ten=torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# can also create a tensor of zeros similar to another tensor
ten_zeros=torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#tensor datatype

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

In [22]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,#default to none,which is torch.float32 or whatever datatype
                             device=None,#default to none,which uses the default tensor type
                             requires_grad=False)# if true , operation perform on tensor are recorded
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

In [23]:
float_16_tensor=torch.tensor([3.0,4.0,5.0],dtype=torch.float16)
float_16_tensor.dtype

torch.float16

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)

dtype - what datatype are the elements within the tensor stored in?

device - what device is the tensor stored on? (usually GPU or CPU)

In [24]:
#Create a tensor
some_tensor=torch.rand(3,4)
#find some details
print(some_tensor)
print(f"shape:{some_tensor.shape}")
print(f"dtype:{some_tensor.dtype}")
print(f"device:{some_tensor.device}")

tensor([[0.5058, 0.9353, 0.5359, 0.6557],
        [0.2305, 0.8588, 0.5367, 0.0280],
        [0.2993, 0.6676, 0.5089, 0.8121]])
shape:torch.Size([3, 4])
dtype:torch.float32
device:cpu


#manipulating tensors(tensor operation)

addition

subtraction

multiplication

division

matrix muliplication

In [25]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [26]:
tensor

tensor([1, 2, 3])

In [27]:
tensor*10

tensor([10, 20, 30])

In [28]:
#we dont see cahin untill reassign
tensor

tensor([1, 2, 3])

In [29]:
tensor=tensor-10
tensor

tensor([-9, -8, -7])

In [30]:
tensor=tensor+10

In [31]:
tensor

tensor([1, 2, 3])

In [32]:
#alternate method
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [34]:
tensor

tensor([1, 2, 3])

In [35]:
#eliment wise multiplication
print(tensor,'*',tensor)
print("equals",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals tensor([1, 4, 9])


Matrix multiplication

One of the most common operation in machine leearning and deep learning algorithms is matrix multipllication
The inner dimensions must match:

.(3, 2) @ (3, 2) won't work

.(2, 3) @ (3, 2) will work

.(3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:

.(2, 3) @ (3, 2) -> (2, 2)

.(3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symb


In [4]:
import torch
tensor=torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

The difference between element-wise multiplication and matrix multiplication is the addition of values.

For our tensor variable with values [1, 2, 3]:

Operation	Calculation	Code

Element-wise multiplication	[1\*1, 2\*2, 3\*3] = [1, 4, 9]	tensor * tensor

Matrix multiplication	[1\*1 + 2\*2 + 3\*3] = [14]	tensor.matmul(tensor)


In [3]:
#element wise multiplication
tensor*tensor

tensor([1, 4, 9])

In [4]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [5]:
#you can also use @ for matrix multiplication
tensor@tensor

tensor(14)

In [6]:
%%time
#matrix multiplication by hand
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 1.6 ms, sys: 114 µs, total: 1.71 ms
Wall time: 8.62 ms


In [7]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 433 µs, sys: 0 ns, total: 433 µs
Wall time: 642 µs


tensor(14)

# one the most commom=n error in deep learning is shape error

Because much of deep learning is multiplication and performing operation on matrix and matrix follow strict rule about shape and size that can be combined.

In [5]:
#Shape and size need to be right way
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,11]])
#torch.matmul(tensor_A,tensor_B)

In [11]:
print(tensor_A)
print(tensor_B.T)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 11]])


In [13]:
print(tensor_A.shape)
print(tensor_B.T.shape)

torch.Size([3, 2])
torch.Size([2, 3])


In [14]:
print(torch.matmul(tensor_A,tensor_B.T))

tensor([[ 27,  30,  31],
        [ 61,  68,  71],
        [ 95, 106, 111]])


In [15]:
#torch.mm is short form of torch.matmul
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  31],
        [ 61,  68,  71],
        [ 95, 106, 111]])

Neural networks are full of matrix multiplications and dot products.

The torch.nn.Linear() module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

y=x.A(transpone) +b


Where:

x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).

A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).

Note: You might also often see W or another letter like X used to showcase the weights matrix.

b is the bias term used to slightly offset the weights and inputs.

y is the output (a manipulation of the input in the hopes to discover patterns in it).

This is a linear function (you may have seen something like y=mx+**c**
 in high school or elsewhere), and can be used to draw a straight line!

Let's play around with a linear layer.

Try changing the values of in_features and out_features below and see what happens.

Do you notice anything to do with the shapes

In [9]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible
torch.manual_seed(42)
#this uses matrix multiplication
linear=torch.nn.Linear(in_features=2,out_features=6)
x=tensor_A.type(torch.float32) # Convert tensor_A to float32
output=linear(x)
print(f"input shape:{x.shape}\n")
print(f"Output:\n{output}\n\n Output shape:{output.shape}")

input shape:torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

 Output shape:torch.Size([3, 6])


# Finding the min, max,mean, sum,etc
now let's run through a few ways to aggegate them



In [10]:
#Create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
print(f"Minimum:{x.min()}")
print(f"Maximum:{x.max()}")
print(f"mean:{x.type(torch.float32).mean()}")
print(f"sum:{x.sum()}")
print(f"standard deviation:{x.type(torch.float32).std()}")

Minimum:0
Maximum:90
mean:45.0
sum:450
standard deviation:30.27650260925293


In [16]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

#positional min/max

In [17]:
#Create a tensor
tensor=torch.arange(10,100,10)
print(f"tensor:{tensor}")

#return index of max and min values
print(f"index where max value occurs:{tensor.argmax()}")
print(f"index where min value occurs:{tensor.argmin()}")


tensor:tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
index where max value occurs:8
index where min value occurs:0


#Reshaping,stacking, squeezing and unsqueezing


Method	One-line description

torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().

Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.

torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.

torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.

torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.

torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.


Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

In [24]:
x=torch.arange(1.,9.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [25]:
x_reshaped=x.reshape(2,4)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [26]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [27]:
z=x.view(2,2,2)
z,z.shape

(tensor([[[1., 2.],
          [3., 4.]],
 
         [[5., 6.],
          [7., 8.]]]),
 torch.Size([2, 2, 2]))

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too

In [36]:
z[0,0,0]=9
z,x

(tensor([[[9., 2.],
          [3., 4.]],
 
         [[5., 6.],
          [7., 8.]]]),
 tensor([9., 2., 3., 4., 5., 6., 7., 8.]))

In [42]:
# Stack tensor over top of each othe
x_stacked=torch.stack([x,x,x,x],dim=1)# try changing dim to dim=0 and see what happens
x_stacked

tensor([[9., 9., 9., 9.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])

In [43]:
#squeeze
print(f"previous shape:{z.shape}")
z_squeezed=z.squeeze()
print(f"new shape:{z_squeezed.shape}")
print(z_squeezed)

previous shape:torch.Size([2, 2, 2])
new shape:torch.Size([2, 2, 2])
tensor([[[9., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


torch.squeeze() only removes dimensions of size 1.

Your tensor shape is:

torch.Size([2, 2, 2])


There is no dimension equal to 1, so PyTorch has nothing to remove.

That’s why:

z_squeezed = z.squeeze()


keeps the same shape:

previous shape: torch.Size([2, 2, 2])
new shape:      torch.Size([2, 2, 2])

Rule of squeeze

It removes only axes where:

size == 1

Example where squeeze works:
z = torch.randn(1, 2, 1, 3)

print(z.shape)        # torch.Size([1, 2, 1, 3])
print(z.squeeze().shape)  # torch.Size([2, 3])

In [44]:
#Unsquzeed
z_unsqueezed=z_squeezed.unsqueeze(dim=0)
print(f"previous shape:{z_squeezed.shape}")
print(f"new shape:{z_unsqueezed.shape}")

previous shape:torch.Size([2, 2, 2])
new shape:torch.Size([1, 2, 2, 2])


You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

In [45]:
x_original=torch.rand(224,224,3)
#permute the original tensor to rearrange the axis order
x_permuted=x_original.permute(2,0,1)
print(f"previous shape:{x_original.shape}")
print(f"new shape:{x_permuted.shape}")

previous shape:torch.Size([224, 224, 3])
new shape:torch.Size([3, 224, 224])


#Indexing (selecting data from tensors)

In [46]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [47]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [48]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [49]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [50]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [51]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

#pytorch and numpy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [52]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [53]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [54]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [55]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproducibility(trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

start with random numbers -> tensor operations -> try to make better (again and again and again)

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where reproducibility comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [58]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8973, 0.3629, 0.1748, 0.2401],
        [0.5457, 0.7303, 0.5268, 0.6694],
        [0.3213, 0.4008, 0.2892, 0.9977]])

Tensor B:
tensor([[0.6649, 0.5646, 0.9323, 0.4621],
        [0.4027, 0.1680, 0.1170, 0.5063],
        [0.6061, 0.5141, 0.1907, 0.0445]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [59]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running tensors on GPUs (and making faster computations)

Google Colab	Easy	Free to use, almost zero setup required, can share work with others as easy as a link	Doesn't save your data outputs, limited compute, subject to timeouts	Follow the Google Colab Guide

Use your own	Medium	Run everything locally on your own machine	GPUs aren't free, require upfront cost	Follow the PyTorch installation guidelines

Cloud computing (AWS, GCP, Azure)	Medium-Hard	Small upfront cost, access to almost infinite compute	Can get expensive if running continually, takes some time to setup right	Follow the PyTorch installation guidelines

There are more options for using GPUs but the above three will suffice for now.

In [1]:
#!nvidia-smi
!nvidia-smi

Sun Jan 11 11:44:33 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# Getting Pytorch to run on the GPU

In [2]:
#check for GPU
import torch
torch.cuda.is_available()

True

In [3]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

If you want to do faster computing you can use a GPU but if you want to do much faster computing, you can use multiple GPUs.

You can count the number of GPUs PyTorch has access to using torch.cuda.device_count().

In [4]:
# Count number of devices
torch.cuda.device_count()

1

In [5]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')